with source as (
      select * from {{ source('bronze', 'bscs_ccontact_all') }}
),
renamed as (
    select
        {{ adapter.quote("customer_id") }},
        {{ adapter.quote("ccseq") }},
        {{ adapter.quote("cctitle") }},
        {{ adapter.quote("ccname") }},
        {{ adapter.quote("ccfname") }},
        {{ adapter.quote("cclname") }},
        {{ adapter.quote("ccstreet") }},
        {{ adapter.quote("ccstreetno") }},
        {{ adapter.quote("cclnamemc") }},
        {{ adapter.quote("ccaddr1") }},
        {{ adapter.quote("ccaddr2") }},
        {{ adapter.quote("ccaddr3") }},
        {{ adapter.quote("cccity") }},
        {{ adapter.quote("cczip") }},
        {{ adapter.quote("cccountry") }},
        {{ adapter.quote("cctn") }},
        {{ adapter.quote("cctn2") }},
        {{ adapter.quote("ccfax") }},
        {{ adapter.quote("ccline1") }},
        {{ adapter.quote("ccline2") }},
        {{ adapter.quote("ccline3") }},
        {{ adapter.quote("ccline4") }},
        {{ adapter.quote("ccline5") }},
        {{ adapter.quote("ccline6") }},
        {{ adapter.quote("cctn_area") }},
        {{ adapter.quote("cctn2_area") }},
        {{ adapter.quote("ccfax_area") }},
        {{ adapter.quote("ccjobdesc") }},
        {{ adapter.quote("ccdeftrk") }},
        {{ adapter.quote("ccuser") }},
        {{ adapter.quote("ccbill") }},
        {{ adapter.quote("ccbilldetails") }},
        {{ adapter.quote("cccontract") }},
        {{ adapter.quote("ccship") }},
        {{ adapter.quote("ccmagazine") }},
        {{ adapter.quote("ccdirectory") }},
        {{ adapter.quote("ccforward") }},
        {{ adapter.quote("ccurgent") }},
        {{ adapter.quote("country") }},
        {{ adapter.quote("cclanguage") }},
        {{ adapter.quote("ccadditional") }},
        {{ adapter.quote("sort_criteria") }},
        {{ adapter.quote("ccentdate") }},
        {{ adapter.quote("ccmoddate") }},
        {{ adapter.quote("ccmod") }},
        {{ adapter.quote("rec_version") }},
        {{ adapter.quote("cczip_addition") }},
        {{ adapter.quote("cccounty") }},
        {{ adapter.quote("ccstate") }},
        {{ adapter.quote("ccgeocode") }},
        {{ adapter.quote("ccvaliddate") }},
        {{ adapter.quote("ccbill_previous") }},
        {{ adapter.quote("welcome_crit") }},
        {{ adapter.quote("ccmname") }},
        {{ adapter.quote("ccemail") }},
        {{ adapter.quote("ccaddryears") }},
        {{ adapter.quote("ccsmsno") }},
        {{ adapter.quote("ccinccode") }},
        {{ adapter.quote("userlastmod") }},
        {{ adapter.quote("ccbilltemp") }},
        {{ adapter.quote("ccvalidation") }},
        {{ adapter.quote("ccuser_inst") }},
        {{ adapter.quote("cclocation_1") }},
        {{ adapter.quote("cclocation_2") }},
        {{ adapter.quote("ccremark") }},
        {{ adapter.quote("dwh_etl_history_fk") }},
        {{ adapter.quote("flg_processed") }},
        {{ adapter.quote("flg_error") }},
        {{ adapter.quote("error_desc") }},
        {{ adapter.quote("stg_record_load_date") }}

    from source
)
select * from renamed
  